// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.db;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(BankContext))]
    partial class BankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication3.Models.Credit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MaxAmount")
                        .HasColumnType("int");

                    b.Property<int>("MaxTermMonths")
                        .HasColumnType("int");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.Property<int>("MinTermMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Credits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Кредит на будь-які потреби без застави",
                            IconClass = "fa-shopping-cart",
                            InterestRate = 18.5m,
                            MaxAmount = 300000,
                            MaxTermMonths = 60,
                            MinAmount = 5000,
                            MinTermMonths = 6,
                            Name = "Споживчий кредит",
                            Requirements = "Паспорт, ІПН, довідка про доходи"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Кредит на придбання нерухомості під заставу",
                            IconClass = "fa-home",
                            InterestRate = 12.9m,
                            MaxAmount = 5000000,
                            MaxTermMonths = 300,
                            MinAmount = 100000,
                            MinTermMonths = 12,
                            Name = "Іпотека",
                            Requirements = "Паспорт, ІПН, довідка про доходи, документи на нерухомість"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Кредит на придбання автомобіля під заставу авто",
                            IconClass = "fa-car",
                            InterestRate = 15.9m,
                            MaxAmount = 1500000,
                            MaxTermMonths = 84,
                            MinAmount = 50000,
                            MinTermMonths = 12,
                            Name = "Автокредит",
                            Requirements = "Паспорт, ІПН, довідка про доходи, водійське посвідчення"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Кредит для розвитку малого та середнього бізнесу",
                            IconClass = "fa-briefcase",
                            InterestRate = 16.5m,
                            MaxAmount = 3000000,
                            MaxTermMonths = 120,
                            MinAmount = 50000,
                            MinTermMonths = 12,
                            Name = "Бізнес кредит",
                            Requirements = "Реєстрація ФОП/ТОВ, бізнес-план, фінансова звітність"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Перекредитування існуючих кредитів за нижчою ставкою",
                            IconClass = "fa-sync-alt",
                            InterestRate = 14.9m,
                            MaxAmount = 1000000,
                            MaxTermMonths = 120,
                            MinAmount = 20000,
                            MinTermMonths = 12,
                            Name = "Рефінансування",
                            Requirements = "Паспорт, ІПН, кредитний договір, довідка про заборгованість"
                        });
                });

            modelBuilder.Entity("WebApplication3.Models.CreditApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreditId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreditId");

                    b.ToTable("CreditApplications");
                });

            modelBuilder.Entity("WebApplication3.Models.CreditApplication", b =>
                {
                    b.HasOne("WebApplication3.Models.Credit", "Credit")
                        .WithMany()
                        .HasForeignKey("CreditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credit");
                });
#pragma warning restore 612, 618
        }
    }
}
