// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.db;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(BankContext))]
    partial class BankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication3.Models.Credit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MaxAmount")
                        .HasColumnType("int");

                    b.Property<int>("MaxTermMonths")
                        .HasColumnType("int");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.Property<int>("MinTermMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Credits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Кредит на будь-які потреби без застави",
                            IconClass = "fa-shopping-cart",
                            InterestRate = 18.5m,
                            MaxAmount = 300000,
                            MaxTermMonths = 60,
                            MinAmount = 5000,
                            MinTermMonths = 6,
                            Name = "Споживчий кредит",
                            Requirements = "Паспорт, ІПН, довідка про доходи"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Кредит на придбання нерухомості під заставу",
                            IconClass = "fa-home",
                            InterestRate = 12.9m,
                            MaxAmount = 5000000,
                            MaxTermMonths = 300,
                            MinAmount = 100000,
                            MinTermMonths = 12,
                            Name = "Іпотека",
                            Requirements = "Паспорт, ІПН, довідка про доходи, документи на нерухомість"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Кредит на придбання автомобіля під заставу авто",
                            IconClass = "fa-car",
                            InterestRate = 15.9m,
                            MaxAmount = 1500000,
                            MaxTermMonths = 84,
                            MinAmount = 50000,
                            MinTermMonths = 12,
                            Name = "Автокредит",
                            Requirements = "Паспорт, ІПН, довідка про доходи, водійське посвідчення"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Кредит для розвитку малого та середнього бізнесу",
                            IconClass = "fa-briefcase",
                            InterestRate = 16.5m,
                            MaxAmount = 3000000,
                            MaxTermMonths = 120,
                            MinAmount = 50000,
                            MinTermMonths = 12,
                            Name = "Бізнес кредит",
                            Requirements = "Реєстрація ФОП/ТОВ, бізнес-план, фінансова звітність"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Перекредитування існуючих кредитів за нижчою ставкою",
                            IconClass = "fa-sync-alt",
                            InterestRate = 14.9m,
                            MaxAmount = 1000000,
                            MaxTermMonths = 120,
                            MinAmount = 20000,
                            MinTermMonths = 12,
                            Name = "Рефінансування",
                            Requirements = "Паспорт, ІПН, кредитний договір, довідка про заборгованість"
                        });
                });

            modelBuilder.Entity("WebApplication3.Models.CreditApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreditId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreditId");

                    b.ToTable("CreditApplications");
                });

            modelBuilder.Entity("WebApplication3.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "м. Київ, вул. Хрещатик, 1",
                            DateOfBirth = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivanov@example.com",
                            FullName = "Іванов Іван Іванович",
                            Phone = "+380501234567",
                            RegistrationDate = new DateTime(2025, 5, 21, 23, 9, 25, 714, DateTimeKind.Local).AddTicks(9827),
                            Status = "Активний",
                            TaxNumber = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Address = "м. Львів, пр. Свободи, 15",
                            DateOfBirth = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "petrenko@example.com",
                            FullName = "Петренко Олена Петрівна",
                            Phone = "+380672345678",
                            RegistrationDate = new DateTime(2024, 11, 21, 23, 9, 25, 714, DateTimeKind.Local).AddTicks(9834),
                            Status = "Активний",
                            TaxNumber = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            Address = "м. Одеса, вул. Дерибасівська, 20",
                            DateOfBirth = new DateTime(1982, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sydorenko@example.com",
                            FullName = "Сидоренко Олег Миколайович",
                            Phone = "+380933456789",
                            RegistrationDate = new DateTime(2024, 5, 21, 23, 9, 25, 714, DateTimeKind.Local).AddTicks(9840),
                            Status = "Активний",
                            TaxNumber = "5555666677"
                        });
                });

            modelBuilder.Entity("WebApplication3.Models.CustomerCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ApprovedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreditId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RemainingDebt")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RepaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreditId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerCredits");
                });

            modelBuilder.Entity("WebApplication3.Models.CustomerService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.ToTable("CustomerServices");
                });

            modelBuilder.Entity("WebApplication3.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PercentageRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Захист на випадок нещасного випадку",
                            IconClass = "fa-shield-alt",
                            IsActive = true,
                            Name = "Страхування життя та здоров'я",
                            PercentageRate = 2.5m,
                            Price = 0m,
                            ServiceType = "Insurance"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Можливість погасити кредит раніше терміну",
                            IconClass = "fa-fast-forward",
                            IsActive = true,
                            Name = "Дострокове погашення без комісії",
                            Price = 500m,
                            ServiceType = "EarlyRepayment"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Перші 3 місяці без процентів",
                            IconClass = "fa-calendar-check",
                            IsActive = true,
                            Name = "Пільговий період",
                            Price = 1000m,
                            ServiceType = "GracePeriod"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Отримання SMS про стан кредиту",
                            IconClass = "fa-mobile-alt",
                            IsActive = true,
                            Name = "SMS-інформування",
                            Price = 50m,
                            ServiceType = "Notification"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Відстрочка платежів до 6 місяців",
                            IconClass = "fa-umbrella-beach",
                            IsActive = true,
                            Name = "Кредитні канікули",
                            Price = 2000m,
                            ServiceType = "PaymentHoliday"
                        });
                });

            modelBuilder.Entity("WebApplication3.Models.CreditApplication", b =>
                {
                    b.HasOne("WebApplication3.Models.Credit", "Credit")
                        .WithMany()
                        .HasForeignKey("CreditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credit");
                });

            modelBuilder.Entity("WebApplication3.Models.CustomerCredit", b =>
                {
                    b.HasOne("WebApplication3.Models.Credit", "Credit")
                        .WithMany("CustomerCredits")
                        .HasForeignKey("CreditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Customer", "Customer")
                        .WithMany("CustomerCredits")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credit");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WebApplication3.Models.CustomerService", b =>
                {
                    b.HasOne("WebApplication3.Models.Customer", "Customer")
                        .WithMany("CustomerServices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Service", "Service")
                        .WithMany("CustomerServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("WebApplication3.Models.Credit", b =>
                {
                    b.Navigation("CustomerCredits");
                });

            modelBuilder.Entity("WebApplication3.Models.Customer", b =>
                {
                    b.Navigation("CustomerCredits");

                    b.Navigation("CustomerServices");
                });

            modelBuilder.Entity("WebApplication3.Models.Service", b =>
                {
                    b.Navigation("CustomerServices");
                });
#pragma warning restore 612, 618
        }
    }
}
